{"level":"error","message":"Something went wrong Something went wrong","stack":"Error: Something went wrong\n    at Object.<anonymous> (C:\\Users\\fazliddin\\Desktop\\vidly\\index.js:36:7)\n    at Module._compile (node:internal/modules/cjs/loader:1239:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)\n    at Module.load (node:internal/modules/cjs/loader:1096:32)\n    at Module._load (node:internal/modules/cjs/loader:935:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:84:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"Something went wrong Something went wrong","stack":"Error: Something went wrong\n    at Object.<anonymous> (C:\\Users\\fazliddin\\Desktop\\vidly\\index.js:37:26)\n    at Module._compile (node:internal/modules/cjs/loader:1239:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)\n    at Module.load (node:internal/modules/cjs/loader:1096:32)\n    at Module._load (node:internal/modules/cjs/loader:935:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:84:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"Something went wrong Something went wrong","stack":"Error: Something went wrong\n    at Object.<anonymous> (C:\\Users\\fazliddin\\Desktop\\vidly\\index.js:37:26)\n    at Module._compile (node:internal/modules/cjs/loader:1239:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)\n    at Module.load (node:internal/modules/cjs/loader:1096:32)\n    at Module._load (node:internal/modules/cjs/loader:935:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:84:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"Something went wrong Something went wrong","stack":"Error: Something went wrong\n    at Object.<anonymous> (C:\\Users\\fazliddin\\Desktop\\vidly\\index.js:37:26)\n    at Module._compile (node:internal/modules/cjs/loader:1239:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)\n    at Module.load (node:internal/modules/cjs/loader:1096:32)\n    at Module._load (node:internal/modules/cjs/loader:935:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:84:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"Something went wrong Something went wrong","stack":"Error: Something went wrong\n    at Object.<anonymous> (C:\\Users\\fazliddin\\Desktop\\vidly\\index.js:43:26)\n    at Module._compile (node:internal/modules/cjs/loader:1239:14)\n    at Module._extensions..js (node:internal/modules/cjs/loader:1293:10)\n    at Module.load (node:internal/modules/cjs/loader:1096:32)\n    at Module._load (node:internal/modules/cjs/loader:935:12)\n    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:84:12)\n    at node:internal/main/run_main_module:23:47"}
{"level":"error","message":"failed to connect to server [ac-d6oxeah-shard-00-01.fwoxgwi.mongodb.net:27017] on first connect [MongoNetworkTimeoutError: connection 4 to ac-d6oxeah-shard-00-01.fwoxgwi.mongodb.net:27017 timed out\n    at TLSSocket.<anonymous> (C:\\Users\\fazliddin\\Desktop\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:425:7)\n    at Object.onceWrapper (node:events:627:28)\n    at TLSSocket.emit (node:events:513:28)\n    at Socket._onTimeout (node:net:565:8)\n    at listOnTimeout (node:internal/timers:564:17)\n    at process.processTimers (node:internal/timers:507:7) {\n  [Symbol(beforeHandshake)]: true\n}] failed to connect to server [ac-d6oxeah-shard-00-01.fwoxgwi.mongodb.net:27017] on first connect [MongoNetworkTimeoutError: connection 4 to ac-d6oxeah-shard-00-01.fwoxgwi.mongodb.net:27017 timed out\n    at TLSSocket.<anonymous> (C:\\Users\\fazliddin\\Desktop\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:425:7)\n    at Object.onceWrapper (node:events:627:28)\n    at TLSSocket.emit (node:events:513:28)\n    at Socket._onTimeout (node:net:565:8)\n    at listOnTimeout (node:internal/timers:564:17)\n    at process.processTimers (node:internal/timers:507:7) {\n  [Symbol(beforeHandshake)]: true\n}]","name":"MongoNetworkError","stack":"MongoNetworkError: failed to connect to server [ac-d6oxeah-shard-00-01.fwoxgwi.mongodb.net:27017] on first connect [MongoNetworkTimeoutError: connection 4 to ac-d6oxeah-shard-00-01.fwoxgwi.mongodb.net:27017 timed out\n    at TLSSocket.<anonymous> (C:\\Users\\fazliddin\\Desktop\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:425:7)\n    at Object.onceWrapper (node:events:627:28)\n    at TLSSocket.emit (node:events:513:28)\n    at Socket._onTimeout (node:net:565:8)\n    at listOnTimeout (node:internal/timers:564:17)\n    at process.processTimers (node:internal/timers:507:7) {\n  [Symbol(beforeHandshake)]: true\n}]\n    at Pool.<anonymous> (C:\\Users\\fazliddin\\Desktop\\vidly\\node_modules\\mongodb\\lib\\core\\topologies\\server.js:441:11)\n    at Pool.emit (node:events:513:28)\n    at C:\\Users\\fazliddin\\Desktop\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:564:14\n    at C:\\Users\\fazliddin\\Desktop\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\pool.js:1014:9\n    at callback (C:\\Users\\fazliddin\\Desktop\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:75:5)\n    at C:\\Users\\fazliddin\\Desktop\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connect.js:103:9\n    at _callback (C:\\Users\\fazliddin\\Desktop\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:333:7)\n    at Connection.errorHandler (C:\\Users\\fazliddin\\Desktop\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:348:7)\n    at Object.onceWrapper (node:events:628:26)\n    at Connection.emit (node:events:513:28)\n    at TLSSocket.<anonymous> (C:\\Users\\fazliddin\\Desktop\\vidly\\node_modules\\mongodb\\lib\\core\\connection\\connection.js:423:10)\n    at Object.onceWrapper (node:events:627:28)\n    at TLSSocket.emit (node:events:513:28)\n    at Socket._onTimeout (node:net:565:8)\n    at listOnTimeout (node:internal/timers:564:17)\n    at process.processTimers (node:internal/timers:507:7)"}
